version: '3'

services:
  sports-barrier-free-liff:
    build: .
    image: sports-barrier-free-liff
    volumes:
      - ".:/app"
      - "/app/node_modules"
    command: "yarn dev:proxy"
    ports:
      - "3001:3001"
